version: '3.8'

services:
  # -------------------------------
  # MariaDB service
  # -------------------------------
  mariadb:
    build:
      context: .
      dockerfile: docker/mariadb.Dockerfile
    container_name: personapp-mariadb
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: persona_db
      MYSQL_USER: persona_db
      MYSQL_PASSWORD: persona_db
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - personapp-network

  # -------------------------------
  # MongoDB service
  # -------------------------------
  mongodb:
    build:
      context: .
      dockerfile: docker/mongodb.Dockerfile
    container_name: personapp-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: persona_db
    networks:
      - personapp-network

  # -------------------------------
  # REST API (Spring Boot)
  # -------------------------------
  personapp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personapp-api
    ports:
      - '3000:3000'
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mariadb
      - mongodb
    networks:
      - personapp-network

  # -------------------------------
  # CLI adapter (optional)
  # -------------------------------
  personapp-cli:
    build:
      context: .
      dockerfile: docker/Dockerfile.cli
    container_name: personapp-cli
    stdin_open: true
    tty: true
    depends_on:
      - mariadb
      - mongodb
    networks:
      - personapp-network

# -------------------------------
# Network and volume definitions
# -------------------------------
networks:
  personapp-network:
    driver: bridge

volumes:
  mariadb_data:
  mongodb_data:
